name: Lint
on:
  push:
    branches-ignore:
      - 'translations**'
  pull_request:
    branches-ignore:
      - 'translations**'
concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  lint:
    name: Linting via prek
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: chainguard-actions/actions-checkout@279383ec3b8d70f964ffa5a2151ea3d2a5317ec6 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Python
        uses: chainguard-actions/actions-setup-python@9bc81c95771c379a24d235203ec35ccbac904e5a # v7.0.0
        with:
          python-version: "3.14"
      - name: Run prek
        uses: chainguard-actions/j178-prek-action@5263d6a82f7afff651213ebc10281c003b865107 # v3.0.0
